### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by ak3264114** [divyansh-2005/my-calendar-app#1]
hi @divyansh-2005,
In this project there is no button and page for login and signup.
i can fix this
Please assign me this issue under GSSOC Extended 2024 :)

![image](https://github.com/user-attachments/assets/5d691c29-c934-4e48-8d70-370c8718c1b8)

**Comment by divyansh-2005** [comment]
@ak3264114 go ahead, but correctly application is facing some error.
you can submit PR mention this issue

**Comment by anuj-cyberSec** [comment]
> hi @divyansh-2005, In this project there is no button and page for login and signup. i can fix this Please assign me this issue under GSSOC Extended 2024 :)
> 
> ![image](https://private-user-images.githubusercontent.com/91682208/372525617-5d691c29-c934-4e48-8d70-370c8718c1b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDk4MTMsIm5iZiI6MTcyNzg0OTUxMywicGF0aCI6Ii85MTY4MjIwOC8zNzI1MjU2MTctNWQ2OTFjMjktYzkzNC00ZTQ4LThkNzAtMzcwYzg3MThjMWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA2MTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MjkwMzNlY2Q5YzY1M2NmMDFlZjQzOTNmYWM0NTUzYTE1ZTZmMTJjMjY4YmJhMmFiMDI0MGI1ZmExZDk3ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zCghYyIdGanyfDbAMJdsdyw9cNr7T3cIEzazDpqFV3M)

@ak3264114 so you are going to develope backend as well as frontend?
