### ISSUE TITLE
[FEATURE] Event Creation, Editing, and Recurring Events Feature

### ISSUE THREAD

**Issue by amitb0ra** [divyansh-2005/my-calendar-app#131]
**Is your feature request related to a problem? Please describe.**
Currently, users are unable to create or edit events in the calendar app, limiting the calendar's functionality to just date display. It would be more useful if users could add events, appointments, or reminders to specific dates, especially with recurring event support.

**Describe the solution you'd like**
I would like to implement a feature that allows users to create, edit, and manage events by clicking on specific dates in the calendar. The event form should include:

Event Name
Time
Description
Priority (low, medium, high)
In addition, I would like to add support for recurring events with options to repeat events daily, weekly, or monthly. Users should also be able to specify how long the event should repeat (e.g., for a set number of occurrences or until a certain date). The events should be visually distinguishable on the calendar.

**Screenshots**

**screenshots/video of feature**

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

Please assign this to me under GSSoC-ext and Hacktoberfest labels. @divyansh-2005

**Comment by anuragcode-16** [comment]
Kindly assign me this issue
