### ISSUE TITLE
[FEATURE] Add Multi-Language Support Using Language Translator

### ISSUE THREAD

**Issue by TBorundia** [divyansh-2005/my-calendar-app#162]
**Is your feature request related to a problem? Please describe.**
Implement a language translation API to allow dynamic switching between multiple languages.
Add a language selector (dropdown or buttons) to the UI for easy language switching.

**check list**
- [X] I am contributing under GSSoC-ext
- [X] I am contributing under hacktoberfest
- [X]  I follow contribution guidlines

**Comment by 33sorbojitmondal** [comment]
Please assign this to me
