### ISSUE TITLE
[FEATURE] Adding feedback form

### ISSUE THREAD

**Issue by TBorundia** [divyansh-2005/my-calendar-app#164]
**Is your feature request related to a problem? Please describe.**
Create a feedback form to collect user input and improve website features. The form should include the following:

Input fields for name, email, and feedback message.
A star rating system for user satisfaction.
Form validation to ensure all fields are correctly filled before submission.
A responsive design that works seamlessly on all devices.
A success/failure message after form submission.

**check list**
- [X] I am contributing under GSSoC-ext
- [X] I am contributing under hacktoberfest
- [X] I follow contribution guidlines

**Comment by Ricky2054** [comment]
Kindly assign me this issue

**Comment by anuragcode-16** [comment]
Kindly assign me this issue

**Comment by anuragcode-16** [comment]
Kindly assign me this issue

**Comment by anuragcode-16** [comment]
Kindly assign me this issue
