### ISSUE TITLE
Enhance the Hero section of website ...

### ISSUE THREAD

**Issue by devxMani** [divyansh-2005/my-calendar-app#19]
Feature
**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Comment by anuza08** [comment]
@devxMani  please assign this issue me 
and I would like to know what enhancement you want.

**Comment by QaisarMoin** [comment]
@devxMani I am contributing under hacktoberfest and also following contribution guidlines. Can you assign me on this issue

**Comment by divyansh-2005** [comment]
@devxMani you should properly make a issue
