### ISSUE TITLE
Propose New Backend Folder Structure for Better Scalability and Maintenance

### ISSUE THREAD

**Issue by Samiran2004** [divyansh-2005/my-calendar-app#2]
I propose to refactor the current backend folder structure of the project to improve organization, scalability, and readability for both current and future contributors. The main goal is to make the codebase easier to navigate and maintain as the project grows.

Reasons for the Change:
Improved Readability: The current backend folder structure has several files and components that could be better organized into logical directories, making it easier for new contributors to find relevant code.
Separation of Concerns: Grouping files by functionality (e.g., separating routes, services, and utilities) will improve the modularity and maintainability of the project.
Scalability: As the project grows, it is important to have a folder structure that supports adding new features without creating clutter.
Best Practices: The new structure will align more closely with best practices, improving the overall development experience.
Proposed Changes:
Separate Core Components: Move key components such as routes, models, services, and utilities into dedicated folders.
Example:
/controllers/authControllers/loginController.js

**Comment by divyansh-2005** [comment]
Not required
