### ISSUE TITLE
Create User Profile page

### ISSUE THREAD

**Issue by aasiflm10** [divyansh-2005/my-calendar-app#21]
**Is your feature request related to a problem? Please describe.**
Right now the project does not  have a UserProfile page. When we click on the User Profile button on the landing page, nothing happens. 

**Describe the solution you'd like**
Create a User Profile page that lists User Details.

**Comment by QaisarMoin** [comment]
Can I work on this Issue ?

**Comment by thaya-rk** [comment]
Hi,I would like to contribute for this enhancement

**Comment by aasiflm10** [comment]
@divyansh-2005 can you please assign this issue to me.

**Comment by taansssss** [comment]
@divyansh-2005  Please assign me this issue. I would like to work on this.
Please assign me under GSSOC'24 extended.

**Comment by aasiflm10** [comment]
@divyansh-2005 is the backend working? I mean the Add Todo functionality is not working.  Also we need to add signin/signup to get user details to show name, email and other info on User's Profile. We can also show the todos on UserProfile( but on my side the Todo functionality does not seem to be working ). 
This is how the current UserProfile page looks. Have a look at it. 
PS : also please tell me if the the project main functionality (like adding todos ) is working fine on your side?

Here is the screen shot : 
![image](https://github.com/user-attachments/assets/4149aa95-7ff6-447c-b501-802b4b81a5c4)

**Comment by divyansh-2005** [comment]
run backend run on localhost it is working.
will deploy backend soon

**Comment by aasiflm10** [comment]
page completed. 
[profilepage.webm](https://github.com/user-attachments/assets/34b4f0bd-17cd-4b25-9887-bc0271d9572f)

Get the userDetails form the api using '/api/auth/me' 
Gets the userTodos from the api using '/api/todos'

Please check and tell shall i generate the Pull req. 
Also there are bugs in the deployed frontend of the application ( like adding todos from the frontend is not working i think its not sending the token correctly ) I had to add todos using postman.

**Comment by aasiflm10** [comment]
i have opened a PR. It has no issues with the main branch. Please review it and let me know. @divyansh-2005

**Comment by divyansh-2005** [comment]
ok
