### ISSUE TITLE
Improve the UI of expense tracker and total to-dos

### ISSUE THREAD

**Issue by kottarivaibhav** [divyansh-2005/my-calendar-app#3]
Hello @divyansh-2005 
This is a simple UI change where I am planning to change the total expense and total-to-dos layout , but can have great impact on the over all UX along with some changes in the design /

I would like to arrange them in column flex when viewed in large devices and row flex when viewed in smaller devices 

This is the current design , which I would like to modify
![image](https://github.com/user-attachments/assets/f1071b5d-d7c8-4237-9373-416b44d27cc2)

so I request you to assign this task to me

**Comment by divyansh-2005** [comment]
share screenshot of proposed change

**Comment by kottarivaibhav** [comment]
@divyansh-2005 I have done the changes . Go through it and accept my pull request
