### ISSUE TITLE
Add Sidebar for Managing Expenses and To-Do List

### ISSUE THREAD

**Issue by anuza08** [divyansh-2005/my-calendar-app#31]
**Is your feature request related to a problem? Please describe.**
Navigating through multiple pages makes it harder to keep track of my tasks and financial entries. A dedicated space for these key features would make the app more user-friendly and organized.

**Describe the solution you'd like**
I would like to add a collapsible sidebar to the application that lists all expenses and to-do items. The sidebar should provide:

A section for displaying and managing all expenses (with options to add, edit, and delete).
A section for a to-do list, allowing users to add new tasks, mark tasks as complete, and delete tasks.
The sidebar should be easy to access from any page and improve workflow by keeping these features readily available.

**Screenshots**
![Screenshot 2024-10-03 192059](https://github.com/user-attachments/assets/5facbf1f-c12e-4d9f-a1b0-aabb9c74de8e)

**check list**
- [✅ ] I am contributing under GSSoC-ext
- [✅ ] I am contributing under hacktoberfest
- [✅ ] I follow contribution guidlines

**Comment by shawaiz-khan** [comment]
I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

**Comment by divyansh-2005** [comment]
its done now
