### ISSUE TITLE
Error in the README.md content

### ISSUE THREAD

**Issue by kottarivaibhav** [divyansh-2005/my-calendar-app#4]
Hello @divyansh-2005 

I have seen that the way to run the current project  is not proper in the README.md document . this might let to lot of confusion to the new-developers.

**To Reproduce**
1. Open the README.md
2. Move to the frontend/backend
3. scroll to the  "frontend/backend" development server:
4. See the error , "npm start" , which is wrong . 
**Expected behavior**
Since Its an Vite+React , it must be stated "npm  run dev "

**Screenshot of the error**
![image](https://github.com/user-attachments/assets/14ec77c4-53e9-4184-af44-b1dd869ad3a8)

**Comment by Dnyaneshpise** [comment]
I would like to work on this as a part of GSSoC and hacktoberfest
