### ISSUE TITLE
[BUG] Changing the old svg of twitter to new X svg.

### ISSUE THREAD

**Issue by Jazz-45** [divyansh-2005/my-calendar-app#42]
**Describe the bug**
The web version uses the old svg of a social media link.

**To Reproduce**
1. Go to 'Solution'
3. Scroll down to 'Footer'

**Expected behavior**
The new logo should be used.

**Screenshots before**
![Screenshot 2024-10-04 181620](https://github.com/user-attachments/assets/55dcc3db-166e-4ca3-93b1-61118e1a617e)

**screenshots after fix***
![image](https://github.com/user-attachments/assets/b16b3e89-7d12-497f-8126-4081821bb9e0)

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Additional context**

**Comment by belkhoujaons** [comment]
can you assign this to me ?

**Comment by QaisarMoin** [comment]
Please assign me this issue.
