### ISSUE TITLE
[BUG]:Add Expense does not add any new Expense 

### ISSUE THREAD

**Issue by haseebzaki-07** [divyansh-2005/my-calendar-app#54]
**Describe the bug**
Adding expense data and on clicking the add expense button does not add any new expense instead shows "No Expense for this Date"

**To Reproduce**
1. Go to "Add Expenses in the Sidebar"
2. Click on "Add Expense after filling out the expense form"
3. See "No expenses for this date"

**Expected behavior**
Ideally it should append a new expense according to the input of the user.

**Screenshots before**

![Screenshot 2024-10-05 111707](https://github.com/user-attachments/assets/ebe25a00-4887-45a4-b399-670932198b05)

**screenshots after fix***

**check list**
- [x ] I am contributing under GSSoC-ext
- [x ] I am contributing under hacktoberfest
- [x ] I follow contribution guidlines

**Comment by konan625** [comment]
@haseebzaki-07 Can you assign this to me.
