### ISSUE TITLE
[FEATURE] Add About us and Contact us pages and also link it with the home page

### ISSUE THREAD

**Issue by yeshwanth-ds** [divyansh-2005/my-calendar-app#55]
### Feature Request

**Is your feature request related to a problem? Please describe.**
I'm frustrated that there is no "About Us" and "Contact Us" page on the site, which makes it difficult for users to learn more about the organization and how to get in touch.

**Describe the solution you'd like**
I would like to create an "About Us" page and a "Contact Us" page. These pages will include relevant information about the organization, team, mission, and ways to get in touch. I will link these pages to the homepage for easy navigation.

**Screenshots**
![Screenshot 2024-10-05 121129](https://github.com/user-attachments/assets/d049be91-97aa-4afd-98eb-421e27e96682)

**Screenshots/Video of Feature**
(Optional: I can create a video or screenshots explaining the feature during the development process.)

### Checklist
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under Hacktoberfest
- [x] I follow contribution guidelines

I will design the "About Us" and "Contact Us" pages, link them to the homepage, and ensure they are populated with appropriate information about the organization.

Please provide me with the necessary codebase access or guidelines to proceed with the development.

**Comment by QaisarMoin** [comment]
Please assign me this issue

**Comment by Sawan-Kushwah** [comment]
can you assign me this i want to work on this issue

**Comment by divyansh-2005** [comment]
@yeshwanth-ds follow color of project and design a simple pages

**Comment by yeshwanth-ds** [comment]
@divyansh-2005 Okay!! I will complet it as soon a possible.

**Comment by yeshwanth-ds** [comment]
@divyansh-2005 I have complet this task and raised a PR #70 . Review this PR and assign me the labels
