### ISSUE TITLE
[FEATURE] Update Navbar to Include Calendar Logo and User Icon

### ISSUE THREAD

**Issue by Dnyaneshpise** [divyansh-2005/my-calendar-app#63]
**Is your feature request related to a problem? Please describe.**
The current navbar lacks a logo and user icon, which detracts from its visual appeal. I have included a screenshot with the added icons that enhance the navbar and give it a more attractive look.

**Screenshots**
SS of current Navbar
![image](https://github.com/user-attachments/assets/f4c69ae1-4e80-4a93-b138-3a4239e4af8d)

**screenshots/video of feature**
SS after updating the Navbar
![image](https://github.com/user-attachments/assets/ba81a4eb-580f-45ae-8e5d-edbfdaacbc81)

**check list**
- [X] I am contributing under GSSoC-ext
- [X] I am contributing under hacktoberfest
- [X] I follow contribution guidelines

I would like to work on this issue. Could you please assign it to me?

**Comment by divyansh-2005** [comment]
raise a pr
