### ISSUE TITLE
[FEATURE]Update The UI of Expenses

### ISSUE THREAD

**Issue by Monu2114** [divyansh-2005/my-calendar-app#64]
**Is your feature request related to a problem? Please describe.**
  The UI is too simple and can be made better with additional CSS features

**Screenshots**
![image](https://github.com/user-attachments/assets/5c505bb1-ce77-48bc-ba4b-d8fc24d712c6)

**check list**
- [x ] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Comment by HemanthTigga** [comment]
May i work on this issue too?
