### ISSUE TITLE
[BUG] Missing name of website/ webpage

### ISSUE THREAD

**Issue by Vishv0407** [divyansh-2005/my-calendar-app#84]
**Describe the bug**
Here on the top of the website/ title of the website/webpage is written " Vite + React " but it needs to be a proper name.

**To Reproduce**
1. Go to 'any page of the website'
2. See at the top tab option.

**Expected behavior**
It should be a proper name for favicon icon.

**Screenshots before**
![image](https://github.com/user-attachments/assets/818acd0c-56ce-4e80-9818-775f619200b5)

**screenshots after fix***

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Additional context**

Can you please tell the name for website/ webpage so i can add it.

**Comment by Dnyaneshpise** [comment]
Duplicate #12
