### ISSUE TITLE
[BUG] fix mobile page ui

### ISSUE THREAD

**Issue by jainaryan04** [divyansh-2005/my-calendar-app#85]
@divyansh-2005 
**Expected behavior**
The left sidebar should be either on top or bottom of the page for better UI on mobile view.

**Screenshots before**
![image](https://github.com/user-attachments/assets/0d98a963-a0a0-4e97-8021-02c5b74d065c)

**check list**
- [ Y ] I am contributing under GSSoC-ext
- [ Y ] I am contributing under hacktoberfest-accepted
- [ Y ] I follow contribution guidlines

**Comment by Dnyaneshpise** [comment]
I would like to work on this issue for improving sidebar UI in mobile
