### ISSUE TITLE
Add an footer to the Page 

### ISSUE THREAD

**Issue by kottarivaibhav** [divyansh-2005/my-calendar-app#9]
hello @divyansh-2005 
So lets answer the questions about the present issue-

**Is your feature request related to a problem? Please describe.**
- Adding a footer is imp , just like header/navbar . It gives better user experience .

**Describe the solution you'd like**
I would like to add a footer , with copyright symbol , certain about us , logo if any , and any other details which You would like me to add

**check list**
- [ ] I am contributing under GSSoC-ext
- [ ] I am contributing under hacktoberfest
- [ ] I follow contribution guidlines

Please accept my issue , and I would like to work on it .
Thankyou

**Comment by Arnavpk** [comment]
I can work on frontend issues and also make your login page UI better. I am contributing under hacktoberfest and also following contribution guidlines. Can you assign me on this issue

**Comment by QaisarMoin** [comment]
@kottarivaibhav I am contributing under hacktoberfest and also following contribution guidlines. Can you assign me on this issue. Please
